### ISSUE TITLE
Help Error: spawn keytool ENOENT

### ISSUE THREAD

**Issue by shubham399** [FrankGrimm/node-keytool#8]
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn keytool ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

**Comment by mklueh** [comment]
In case anyone has the same error, it´s likely that the keytool hasn´t been added to your environment variables
